#!/bin/bash

SINK=$(pactl list short sinks | grep RUNNING | cut -f1)
VOLUME=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
MUTED=$(pactl list sinks | grep '^[[:space:]]Mute:' | head -n $(( $SINK + 1 )) | tail -n 1 | cut -f2 -d " ")

if [ "$MUTED" == "yes" ]
then
   echo "MUTE"
else
   echo "$VOLUME%"
fi
